language: node_js

node_js:
  - '4.2'

sudo: false

cache:
  directories:
    - node_modules
    - vendor/bundle

git:
  submodules: false

before_install:
  - gem install bundler
  - bundle install --path vendor/bundle
  - npm install -g grunt-cli

script:
  - npm start